services:
  - type: web
    name: serial-bot-gsheets
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_webhook.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_WEBHOOK_SECRET
        generateValue: true
      - key: GOOGLE_SERVICE_JSON
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_SHEET_NAME
        value: ""
      - key: CACHE_TTL_SECONDS
        value: "300"
      - key: TZ
        value: Asia/Ho_Chi_Minh
